services:
  tourney-overlay:
    image: ghcr.io/deihatchi/tourney-overlay:latest
    container_name: tourney-overlay
    ports:
      - "8002:8000"
    volumes:
      - tourney-overlay-data:/app/app/static/avatars
    restart: unless-stopped

volumes:
  tourney-overlay-data:
